onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver

patchedDependencies:
  vite-plugin-storybook-nextjs@2.0.8: patches/vite-plugin-storybook-nextjs@2.0.8.patch
