name: Build
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Set environment variables
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          touch .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/login" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/home" >> .env
          echo "CLERK_SECRET_KEY=${CLERK_SECRET_KEY}" >> .env
          echo "WEBHOOK_SECRET=${WEBHOOK_SECRET}" >> .env
          echo "POSTGRES_PRISMA_URL=postgresql://user:pass@localhost:5432/db?schema=public" >> .env
      - name: Build
        run: pnpm build
