name: Lint
on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/prepare
      - name: Build workspace packages
        run: pnpm --filter eslint-plugin-dslint build
      - name: Lint
        run: pnpm lint
      - name: Lint workspace packages
        run: pnpm --filter eslint-plugin-dslint lint
