name: Lint
on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/prepare
      - name: Build workspace packages
        run: pnpm --filter eslint-plugin-dslint build
      - name: Lint
        run: pnpm lint
      - name: Lint workspace packages
        run: pnpm --filter eslint-plugin-dslint lint
