name: Storybook Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  # Allow manual workflow dispatch
  workflow_dispatch:

env:
  NODE_VERSION: '22.17.1'

jobs:
  storybook-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Run Storybook tests
        run: pnpm test:storybook --run

      - name: Upload Storybook test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-test-results
          path: storybook-test-results/
          retention-days: 7
